<?php

namespace OiLab\OiLaravelAttachments\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Model;
use OiLab\OiLaravelAttachments\Models\Attachment;
use OiLab\OiLaravelAttachments\OiLaravelAttachments;

/**
 * Factory for generating Attachment model instances.
 *
 * @extends Factory<Attachment>
 */
class AttachmentFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string
     */
    public function modelName(): string
    {
        return OiLaravelAttachments::attachmentModel();
    }

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'file_id' => OiLaravelAttachments::fileModel()::factory(),
            'attachable_type' => OiLaravelAttachments::userModel(),
            'attachable_id' => OiLaravelAttachments::userModel()::factory(),
            'sort' => 0,
            'created_by' => null,
            'updated_by' => null,
        ];
    }

    /**
     * Set the sort for this attachment.
     */
    public function sort(int $sort): static
    {
        return $this->state(fn (array $attributes) => [
            'sort' => $sort,
        ]);
    }

    /**
     * Attach to a specific file.
     */
    public function forFile(Model|int $file): static
    {
        return $this->state(fn (array $attributes) => [
            'file_id' => $file instanceof Model ? $file->id : $file,
        ]);
    }
}
