<?php

namespace OiLab\OiLaravelAttachments\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use OiLab\OiLaravelAttachments\Models\File;
use OiLab\OiLaravelAttachments\OiLaravelAttachments;

/**
 * Factory for generating File model instances.
 *
 * @extends Factory<File>
 */
class FileFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string
     */
    public function modelName(): string
    {
        return OiLaravelAttachments::fileModel();
    }

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $fileExtension = fake()->randomElement(['jpg', 'png', 'pdf', 'txt', 'doc']);
        $filename = fake()->uuid().'.'.$fileExtension;

        return [
            'filename_disk' => $filename,
            'filename_download' => fake()->word().'.'.$fileExtension,
            'title' => fake()->optional()->sentence(3),
            'description' => fake()->optional()->sentence(),
            'mimetype' => $this->getMimetypeForExtension($fileExtension),
            'filesize' => fake()->numberBetween(1024, 10485760),
            'width' => null,
            'height' => null,
            'storage' => 'local',
            'metadata' => [],
            'folder_id' => null,
            'created_by' => OiLaravelAttachments::userModel()::factory(),
            'updated_by' => null,
        ];
    }

    /**
     * Get mimetype for file extension.
     *
     * @param  string  $extension  The file extension
     * @return string The corresponding MIME type
     */
    private function getMimetypeForExtension(string $extension): string
    {
        return match ($extension) {
            'jpg', 'jpeg' => 'image/jpeg',
            'png' => 'image/png',
            'gif' => 'image/gif',
            'pdf' => 'application/pdf',
            'txt' => 'text/plain',
            'doc' => 'application/msword',
            default => 'application/octet-stream',
        };
    }

    /**
     * Create an image file with dimensions.
     */
    public function image(): static
    {
        $extension = fake()->randomElement(['jpg', 'png', 'gif']);

        return $this->state(fn (array $attributes) => [
            'filename_disk' => fake()->uuid().'.'.$extension,
            'filename_download' => fake()->word().'.'.$extension,
            'mimetype' => $this->getMimetypeForExtension($extension),
            'width' => fake()->numberBetween(100, 4000),
            'height' => fake()->numberBetween(100, 4000),
        ]);
    }

    /**
     * Create a PDF file.
     */
    public function pdf(): static
    {
        return $this->state(fn (array $attributes) => [
            'filename_disk' => fake()->uuid().'.pdf',
            'filename_download' => fake()->word().'.pdf',
            'mimetype' => 'application/pdf',
        ]);
    }

    /**
     * Place the file in a folder.
     *
     * @param  int|null  $folderId  The folder ID, or null to create a new folder
     */
    public function inFolder(?int $folderId = null): static
    {
        return $this->state(fn (array $attributes) => [
            'folder_id' => $folderId ?? OiLaravelAttachments::folderModel()::factory(),
        ]);
    }

    /**
     * Set custom metadata.
     *
     * @param  array<string, mixed>  $metadata  The metadata to attach to the file
     */
    public function withMetadata(array $metadata): static
    {
        return $this->state(fn (array $attributes) => [
            'metadata' => $metadata,
        ]);
    }
}
