<?php

namespace OiLab\OiLaravelAttachments\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use OiLab\OiLaravelAttachments\Models\Folder;
use OiLab\OiLaravelAttachments\OiLaravelAttachments;

/**
 * Factory for generating Folder model instances.
 *
 * @extends Factory<Folder>
 */
class FolderFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string
     */
    public function modelName(): string
    {
        return OiLaravelAttachments::folderModel();
    }

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->word(),
            'parent_id' => null,
            'created_by' => OiLaravelAttachments::userModel()::factory(),
            'updated_by' => null,
        ];
    }

    /**
     * Create a subfolder with a parent.
     *
     * @param  int|null  $parentId  The parent folder ID, or null to create a new parent
     */
    public function withParent(?int $parentId = null): static
    {
        return $this->state(fn (array $attributes) => [
            'parent_id' => $parentId ?? OiLaravelAttachments::folderModel()::factory(),
        ]);
    }

    /**
     * Create a root folder (no parent).
     */
    public function root(): static
    {
        return $this->state(fn (array $attributes) => [
            'parent_id' => null,
        ]);
    }
}
